[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = [
  'npm run build',
  'node post-build.js'
]

[start]
cmd = 'NODE_ENV=production node dist/index.js'
